export enum NotificationType {
  DOCUMENT_EXPIRING = 'DOCUMENT_EXPIRING',
  DOCUMENT_EXPIRED = 'DOCUMENT_EXPIRED',

  BILL_UPCOMING = 'BILL_UPCOMING',
  BILL_DUE_TODAY = 'BILL_DUE_TODAY',
  BILL_OVERDUE = 'BILL_OVERDUE',

  BUDGET_THRESHOLD = 'BUDGET_THRESHOLD',
  BUDGET_EXCEEDED = 'BUDGET_EXCEEDED',
  BUDGET_ENDING = 'BUDGET_ENDING',

  SAVING_GOAL_REMINDER = 'SAVING_GOAL_REMINDER',
  SAVING_GOAL_COMPLETED = 'SAVING_GOAL_COMPLETED',
  SAVING_GOAL_DEADLINE = 'SAVING_GOAL_DEADLINE',

  WALLET_LOW_BALANCE = 'WALLET_LOW_BALANCE',
}
