export enum UserStatus {
  PENDING = 'PENDING',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  PHONE_VERIFIED = 'PHONE_VERIFIED',
  PIN_CREATED = 'PIN_CREATED',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
}
