export enum TransactionType {
  INCOME = 'INCOME',
  EXPENSE = 'EXPENSE',
  TRANSFER_TO_SAVING = 'TRANSFER_TO_SAVING',
  TRANSFER_FROM_SAVING = 'TRANSFER_FROM_SAVING',
  OPENING_BALANCE = 'OPENING_BALANCE',
}
