import { PaymentMethod } from '../enums/payment-method.enum';
import { TransactionType } from '../enums/transaction-type.enum';
import { ICategory } from './category.interface';

/**
 * @interface ITransaction
 *
 * @description
 * Represents the raw database record shape of a transaction row.
 * This is what Sequelize returns after a query — the exact column mapping
 * from the `transactions` table, including the JOINed category.
 *
 * WHY THIS EXISTS:
 * The Service layer must work with strongly-typed data from the Repository.
 * Without this interface, you would need `any` or `unknown` casts, which
 * defeats the purpose of TypeScript and makes refactoring dangerous.
 *
 * RESPONSIBILITY:
 * This interface is the contract between the Repository Layer and the
 * Service Layer. The Repository returns ITransaction objects. The Service
 * reads them to apply business logic and build the response.
 *
 * WHEN TO USE:
 * - Repository return types
 * - Service internal processing
 * - NOT for API responses (use ITransactionResponse for that)
 *
 * POSTGRESQL CONTEXT:
 * Every field here maps to a column in the `transactions` table.
 * `category` is a nested object from the LEFT JOIN on `categories`.
 *
 * FINANCIAL PRECISION NOTE:
 * `amount` is typed as `number`. Sequelize maps NUMERIC(15,2) to JS number.
 * For applications requiring extreme precision (>15 significant digits),
 * use the `decimal.js` library and type as `Decimal`. For a personal expense
 * tracker, `number` with NUMERIC(15,2) is sufficient and safe.
 *
 * DATE HANDLING:
 * `transaction_date` is a DATE column (no time component). Sequelize maps
 * it to a JavaScript Date at midnight UTC. Always use `.toISOString().split('T')[0]`
 * when displaying — never format it directly without normalizing timezone.
 * `created_at` and `updated_at` are TIMESTAMPTZ (timezone-aware).
 */
export interface ITransaction {
  /** UUID primary key — generated by PostgreSQL gen_random_uuid() */
  readonly id: string;

  /**
   * FK → users.id
   * The authenticated user who owns this transaction.
   * Every query MUST filter by this field to prevent cross-user data access.
   */
  readonly userId: string;

  /**
   * FK → wallets.id
   * The wallet affected by this transaction.
   */
  readonly walletId: string;

  /**
   * FK → categories.id
   * The category this transaction belongs to.
   * Nullable because some types (e.g. OPENING_BALANCE, TRANSFER) do not use categories.
   */
  readonly categoryId: string | null;

  /**
   * FK → saving_goals.id
   * The saving goal affected by this transaction.
   * Nullable because most transactions do not involve saving goals.
   */
  readonly savingGoalId: string | null;

  /**
   * The type of transaction (INCOME, EXPENSE, etc.)
   */
  readonly type: TransactionType;

  /**
   * The full amount of this transaction.
   * MUST be positive — direction (in/out) is determined by category.type.
   * NUMERIC(15,2) in PostgreSQL → supports values up to 9,999,999,999,999.99.
   *
   * Business rule: category.type === INCOME means money received.
   *               category.type === EXPENSE means money spent.
   */
  readonly amount: number;

  /**
   * The calendar date on which this financial event occurred.
   * This is the USER-REPORTED date, not the system creation date.
   * Example: a bank statement from June 15 imported on June 20 has
   * transaction_date = June 15, but created_at = June 20.
   */
  readonly transactionDate: Date;

  /**
   * How the payment was made or received.
   * Constrained to PaymentMethod enum values.
   */
  readonly paymentMethod: PaymentMethod;

  /**
   * Optional free-text note from the user.
   * Examples: "Dinner with family", "Monthly Netflix subscription"
   * No business logic depends on this field — it is purely for user reference.
   */
  readonly note: string | null;

  /**
   * The joined category record.
   * Available when the Repository query includes the category association.
   */
  readonly category?: ICategory;

  /** Audit: when this record was created (server-side, auto-set by DB) */
  readonly createdAt: Date;

  /** Audit: when this record was last updated (auto-updated on every write) */
  readonly updatedAt: Date;

  /**
   * Soft delete timestamp.
   * NULL → record is active.
   * Non-NULL → record has been soft deleted on this date.
   *
   * IMPORTANT: All queries MUST include a `WHERE deleted_at IS NULL`
   * condition (Sequelize: `paranoid: true`). The Repository layer
   * enforces this — the Service layer must never manually filter by this field.
   */
  readonly deletedAt: Date | null;
}
